# Generated by Django 5.0.2 on 2025-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="postal_code",
        ),
        migrations.AddField(
            model_name="abstractcustomuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
