# Generated by Django 5.0.2 on 2025-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_address_postal_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abstractcustomuser",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="buyer",
            name="is_verified_buyer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seller",
            name="is_verified_seller",
            field=models.BooleanField(default=False),
        ),
    ]
