# Generated by Django 5.0.2 on 2025-04-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_remove_abstractcustomuser_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="user_type",
            field=models.CharField(default="buyer", max_length=10),
        ),
        migrations.AddField(
            model_name="seller",
            name="user_type",
            field=models.CharField(default="seller", max_length=10),
        ),
    ]
