get http://localhost:8000/product/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1Njg4NjIzLCJpYXQiOjE3NDU2ODUwMjMsImp0aSI6IjRlOWVhNTJlNTU4NjQzOWVhNzM4NDZmNWUwYzc3ODE5IiwidXNlcl9pZCI6ImMzOTUxYjJhLTczOGUtNDc4NC1iMzk3LWUzYWZmOGEyNmU3YSJ9.8PxRZAbHcJeXv8kXp_Jo-zRSORo7KxEZVOX2axWHk_8