get http://localhost:8000/product/all?page=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTc2OTAxLCJpYXQiOjE3NDU1NzMzMDEsImp0aSI6ImZmYWQ5NmU1YmRiMjRkM2Q4MzM5NjVkMGRiMTFhMWU3IiwidXNlcl9pZCI6IjhjNjNhZmNjLTdlM2EtNGIzZS05OWZmLTU0OTZhODA4OWFlZiJ9.2P0z_S2nxgf78R9Xkt8v91v1MtSXAwHzGi4wd5l3qWU