get http://localhost:8000/product/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NjAxODkyLCJpYXQiOjE3NDU1OTgyOTIsImp0aSI6ImM5NzUyMzdkODgwNjQ4NjZiY2Q4MmE2ODc5MTU1NTRjIiwidXNlcl9pZCI6ImMzOTUxYjJhLTczOGUtNDc4NC1iMzk3LWUzYWZmOGEyNmU3YSJ9.SbH2fyBWi1FfNCu6W_kk_epBf1XCnAPaiE4ryt-bEG0