### Update Buyer KYC
PUT http://localhost:8000/auth/buyer/kyc/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkxNjgyLCJpYXQiOjE3NDU1ODgwODIsImp0aSI6IjQ2ZDhhMmRiYTc2ZjQxOGRhZjRmZWE4N2JmODNmZDY1IiwidXNlcl9pZCI6ImMzOTUxYjJhLTczOGUtNDc4NC1iMzk3LWUzYWZmOGEyNmU3YSJ9.4U3-tt7KjU0BHHT9L3KQEjGSdhGAZ-_lDLGtf2w4J-E

{
  "first_name": "Mojibola",
  "last_name": "Olalekan",
  "phone_number": "+2349067914516",
  "address": {
    "street": "123 Example Street",
    "city": "Osogbo",
    "state": "Osun",
    "country": "Nigeria",
    "label": "Home"
  }
}
