get http://localhost:8000/product/city/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2OTA2NzYyLCJpYXQiOjE3NDY5MDMxNjIsImp0aSI6ImVlODJlMTkxY2E0MzQyYjViNGIyOGM0ODdjNTVmYjhmIiwidXNlcl9pZCI6Ijg3OTg3MGM0LTg0YTQtNGViMy1iNmIyLTMwYjAyZTg4NjBjYyJ9.LWbw6nkiedGzmCZtS-nH8P7rq518Nx6yryi_e_R2O4k