get http://localhost:8000/trade/bid/da2c0658-0c42-4d54-90c8-286f072c73f0/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1Nzk3MDA5LCJpYXQiOjE3NDU3OTM0MDksImp0aSI6IjliZWViZDc0YzA2MjQxOThhZGQyOTY2NTk4MDU5YzVkIiwidXNlcl9pZCI6IjYzNTc3ZDI3LTllM2QtNGQ3OC04NmRlLWMxMzVhMzA4MDE3NSJ9.j5FsLwzVO5t6EnjReLJAwEcTbn_IBK9TJT5UjWCX0g4
