POST http://localhost:8000/product/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkyMDAzLCJpYXQiOjE3NDU1ODg0MDMsImp0aSI6IjNjZTYyNDEyZmRlZjQ0Mjg4MjJmZjlkYzA5OTgwOTc3IiwidXNlcl9pZCI6IjYzNTc3ZDI3LTllM2QtNGQ3OC04NmRlLWMxMzVhMzA4MDE3NSJ9.cibSZ9ow4elcEaHSAnH4xjLpr2xqYpLok86OWjo5YZ8
Content-Type: application/json

{
  "name": "Ferrari F8",
  "description": "A reliable and fuel-efficient sedan.",
  "price": 2000000,
  "quantity": 2,
  "condition": "new",
  "city": "Osogbo",
  "state": "Osun",
  "country": "Nigeria",
  "categories": ["Kids", "Home"]
}
