POST http://localhost:8000/product/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTc3MTY3LCJpYXQiOjE3NDU1NzM1NjcsImp0aSI6Ijc0OWE5MzZiNTg0MjQzNGQ4ZjA1NjA0OGIzNmViNjM4IiwidXNlcl9pZCI6ImI2MGY5YTU4LTM1ZDktNDJiZi05NDY3LTNjMDY5MTQyMTdjYyJ9.Ct2rY6bcu3u4L1NE_o_8jQpMV3f_H6xqQKuM2R9IVQ8
Content-Type: application/json

{
  "name": "Ferrari F8",
  "description": "A reliable and fuel-efficient sedan.",
  "price": 2000000,
  "quantity": 2,
  "condition": "new",
  "city": "Jos",
  "categories": ["Kids", "Home"]
}
