get http://localhost:8000/product/city/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkyODM0LCJpYXQiOjE3NDU1ODkyMzQsImp0aSI6IjE1NGI4MWRmM2EzZDQ5ZTNhMDJlZTE2NGY1ZmI4MDAxIiwidXNlcl9pZCI6ImMzOTUxYjJhLTczOGUtNDc4NC1iMzk3LWUzYWZmOGEyNmU3YSJ9.r3v97NJxCBzZj4Xe4idOD-ZPg3vXZKE4cUF4jhM-sQ8