POST http://localhost:8000/auth/signup/user/
Content-Type: application/json

{
    "email": "lekanmojibola@gmail.com",
    "password": "oladev123"
}

# {
#     "email": "oladev123@gmail.com",
#     "password": "seller123"
# }

# {
#     "email": "lekan4jesu@gmail.com",
#     "password": "seller123"
# }