post http://localhost:8000/auth/switch-role/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2OTE1OTExLCJpYXQiOjE3NDY5MTIzMTEsImp0aSI6IjAxM2ZlMmExNWRjMDQ4ZWVhMTNjYjRhOGZhYmI3MWQ2IiwidXNlcl9pZCI6Ijg3OTg3MGM0LTg0YTQtNGViMy1iNmIyLTMwYjAyZTg4NjBjYyJ9.bGJ2sryJjsRSxeGe-2Zfqx7X2MKexW7ErybaH5Tkvjk

{
    "new_role": "seller"
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NzQ5MDQ0LCJpYXQiOjE3NDY3NDU0NDQsImp0aSI6IjBiY2RhZTFkZTU1YTRlYzI4OTBmNjU2MmUzYWM1MGY0IiwidXNlcl9pZCI6Ijg3OTg3MGM0LTg0YTQtNGViMy1iNmIyLTMwYjAyZTg4NjBjYyJ9.LRNBX-T7vOh2F6GJUpUfXNy2UTVyJbHo3O06CtblW8U