patch http://localhost:8000/product/update/6334ffa7-8452-4a72-827d-dcb279623972/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NzQ3NzQ0LCJpYXQiOjE3NDY3NDQxNDQsImp0aSI6IjE0NWU4NjE2M2JhZDQ5NTQ4MTY4ZDA0ZjQyZGI1MTkxIiwidXNlcl9pZCI6IjhjZmZmYTNlLTE0OTItNGFhNy04YzhjLTQ1NTBlYWNmNWU1YyJ9.V_gJoyS6b5X2sj1KLkxA9YiXulfWdtCRVAJ8PMXTAyE

{
    "city": "Osogbo",
    "state": "Osun"
}