post http://localhost:8000/auth/verify-email/
Content-Type: application/json

# {
#     "email": "oladev123@gmail.com",
#     "otp": "2042"
# }

# {
#     "email": "lekanmojibola@gmail.com",
#     "otp": "5843"
# }

{
    "email": "lekan4jesu@gmail.com",
    "otp": "9653"
}