# Generated by Django 5.0.2 on 2025-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
