# Generated by Django 5.2 on 2025-04-04 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='duration_of_usage',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('fairly_used', 'Fairly Used'), ('old', 'Old')], default='fairly_used', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(choices=[('general', 'General'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_appliances', 'Home Appliances'), ('books', 'Books'), ('toys', 'Toys & Games'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('automotive', 'Automotive'), ('groceries', 'Groceries'), ('furniture', 'Furniture'), ('phones', 'Mobile Phones'), ('computers', 'Computers & Accessories'), ('jewelry', 'Jewelry & Watches'), ('tools', 'Tools & Hardware'), ('music', 'Musical Instruments'), ('baby', 'Baby Products'), ('pets', 'Pet Supplies'), ('health', 'Health & Wellness'), ('gaming', 'Gaming'), ('stationery', 'Stationery & Office Supplies')], default='general', related_name='products', to='product.category'),
        ),
    ]
